version: '3.4'

services:
  flask:
    container_name: app
    restart: unless-stopped
    build:
      context: app
      dockerfile: dev.Dockerfile
    expose:
      - 5000
    ports: [ "5000:5000" ]
    environment:
      FLASK_DEBUG: "True"
      FLASK_PORT: 5000
      FLASK_SECRET: secret
      FLASK_ENV: development
      MONGODB_HOSTNAME: mongodb
      MONGODB_DATABASE: formpydb
    command: sleep infinity
    depends_on:
      - mongodb
    volumes:
      - .:/workspace:cached

  mongodb:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: formpydb
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - ./mongodb/home/mongodb:/home/mongodb
